// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cloud_logic': 'enable',
    'aws_cloud_logic_custom': [{"id":"6099uy4jq2","name":"mediaCRUD","description":"","endpoint":"https://6099uy4jq2.execute-api.us-east-1.amazonaws.com/Development","region":"us-east-1","paths":["/media","/media/123"]}],
    'aws_cognito_identity_pool_id': 'us-east-1:8dc615df-3af1-48e5-90fd-cc8e2cffaee7',
    'aws_cognito_region': 'us-east-1',
    'aws_mobile_analytics_app_id': '377705e9996442f88deed3565f44a65d',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': 'edcdefd2-7699-4c68-b5f3-48b9f85357a1',
    'aws_project_name': 'Candid',
    'aws_project_region': 'us-east-1',
    'aws_resource_bucket_name': 'candid-deployments-mobilehub-1124912258',
    'aws_resource_name_prefix': 'candid-mobilehub-1124912258',
    'aws_user_files': 'enable',
    'aws_user_files_s3_bucket': 'candid-userfiles-mobilehub-1124912258',
    'aws_user_files_s3_bucket_region': 'us-east-1',
}

export default awsmobile;
